// report.js – baut den Fehlerbericht (Markdown). Sendet NICHTS; der Nutzer prüft und meldet selbst.
const fence = (lang, s) => '```' + lang + '\n' + s + '\n```';

export function buildReport(d, { summary, steps, lang }) {
  const en = lang === 'en';
  const lines = [
    `## ${en ? 'What happened' : 'Was ist passiert'}`, summary, '',
    `## ${en ? 'Steps to reproduce' : 'Schritte zum Nachstellen'}`, steps || (en ? '(please add)' : '(bitte ergänzen)'), '',
    `## ${en ? 'Environment' : 'Umgebung'}`,
    `- Board: ${d.boardName} (\`${d.boardId}\`), ${en ? 'connected' : 'verbunden'}: ${d.serial}`,
    `- lib/ ${en ? 'version' : 'Version'}: \`${(d.libVersion || '?').slice(0, 12)}\``,
    `- ${en ? 'Editor language' : 'Editor-Sprache'}: ${d.lang}`,
    `- ${en ? 'Browser' : 'Browser'}: ${d.userAgent}`, '',
    `## ${en ? 'Blocks (workspace JSON)' : 'Blöcke (Workspace-JSON)'}`, fence('json', JSON.stringify(d.workspace, null, 1)), '',
    `## ${en ? 'Generated code' : 'Erzeugter Code'}`, fence('python', d.python), '',
  ];
  if (d.codeEditorDiffers) lines.push(`## ${en ? 'Code pane was edited by hand' : 'Code-Feld wurde von Hand geändert'}`, fence('python', d.codeEditorText), '');
  if (d.warnings.length) lines.push(`## ${en ? 'Block warnings' : 'Block-Warnungen'}`, ...d.warnings.map(w => `- ${w.type}: ${w.text}`), '');
  lines.push(`## ${en ? 'Board console (last lines)' : 'Board-Konsole (letzte Zeilen)'}`, fence('', d.consoleTail || ''), '');
  if (d.jsErrors.length) lines.push(`## ${en ? 'Browser console' : 'Browser-Konsole'}`, fence('', d.jsErrors.map(e => `[${e.level}] ${e.msg}`).join('\n')), '');
  lines.push(en ? '_Generated by makerSpaceOS MCP. Please review for personal data before posting._' : '_Erzeugt vom makerSpaceOS-MCP. Bitte vor dem Absenden auf persönliche Daten prüfen._');
  return lines.join('\n');
}

export const REPORT_TARGETS = ['https://kidslab.de', 'https://github.com/KidsLabDe/makerSpaceOS-Editor/issues'];
